version: "3.7"

services:
  stripe_project:
    restart: always
    build:
      context: ./stripe_project
    command: ./wait-for-it.sh stripe_db:5432 -- python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    depends_on:
      - stripe_db


  stripe_db:
    image: postgres
    restart: always
    ports:
      - 54321:5432
    environment:
      - ./stripe_project/.env
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

